805 806 807 Fix week available for offer
betagouv/monstage pull request #1046
Opened 2023-09-19 10:11 UTC by pierrax

2023-09-19 13:04 UTC, fitchMitch requested changes

2023-09-20 08:25 UTC, pierrax commented on app/controllers/dashboard/internship_offers_controller.rb
> +          @available_weeks = Week.selectable_on_school_year
yes fixed

2023-09-20 08:25 UTC, pierrax commented on app/controllers/dashboard/internship_offers_controller.rb
> +      @available_weeks = Week.selectable_on_school_year
yes fixed

2023-09-20 08:26 UTC, pierrax commented on app/models/concerns/stepper_proxy/internship_offer_info.rb
>        raise 'Wrong !!' unless persisted? && respond_to?(:weeks) # temporary
yes fixed

2023-09-20 08:26 UTC, pierrax commented on app/controllers/dashboard/internship_offers_controller.rb
> +      @available_weeks = Week.selectable_on_school_year
yes fixed

2023-09-20 11:48 UTC, closed without merging