820 Fix school management dashboard side menu
betagouv/monstage pull request #1061
Opened 2023-09-26 12:19 UTC by pierrax

2023-09-26 16:09 UTC, fitchMitch requested changes

2023-09-26 16:09 UTC, fitchMitch commented on app/views/dashboard/internship_agreements/index.html.slim
> += render 'layouts/breadcrumb', links: [ ['', current_user.dashboard_name] ]
la dernière fois que l'on a changé render layout: '....' ,  pour adopter une autre forme, ça a cassé la mise en forme de la page. Render layout est une forme de yield pour les templates. Je ne sais si tu as vérifié que tout était à la bonne place a posteriori

2023-09-27 08:27 UTC, pierrax commented on app/views/dashboard/internship_agreements/index.html.slim
> += render 'layouts/breadcrumb', links: [ ['', current_user.dashboard_name] ]
yes j'ai vérifié, la page s'affiche comme attendu.

2023-09-27 12:59 UTC, fitchMitch approved these changes

2023-10-04 08:12 UTC, merged