801 Internal tracking
betagouv/monstage pull request #1070
Opened 2023-10-04 10:10 UTC by pierrax

2023-10-09 08:06 UTC, fitchMitch requested changes
Il n'y a pas de test system. Est-ce que tu peux les traiter en local ou bien as-tu toujours ce problème de conf avec la nécessité de bloquer Chrome dans sa version 114 ?

2023-10-09 08:06 UTC, fitchMitch commented on app/controllers/internship_offers_controller.rb
> +        current_user.log_search_history(@params.merge({results_count: data[:seats]})) if current_user && current_user.student?
`current_user&.student?`  pourrait remplacer `current_user && current_user.student?`

2023-10-09 08:06 UTC, fitchMitch commented on app/controllers/internship_offers_controller.rb
> +        current_user.log_search_history(@params.merge({results_count: data[:seats]})) if current_user && current_user.student?
dans la partie supérieure du code dans cette méthode, il y a le cas html et je vois qu'on n'y logue pas les événements. C'est normal ?

2023-10-11 12:28 UTC, pierrax commented on app/models/users_internship_offers_history.rb
> +class UsersInternshipOffersHistory < ActiveRecord::Base
C'est le log de la relation user / offer. Ou autrement dit l'activité d'un user sur une offre

2023-10-11 12:35 UTC, pierrax commented on app/views/internship_applications/call_to_action/_api.html.slim
> +  - elsif current_user.nil?
yes, on allège on allège

2023-10-11 12:38 UTC, pierrax commented on app/controllers/internship_offers_controller.rb
> +        current_user.log_search_history(@params.merge({results_count: data[:seats]})) if current_user && current_user.student?
Ca logguerait en double. On passe 2 fois au même endroit. La première pour afficher la page, la seconde pour afficher les résultats de la recherche en asynchrone

2023-10-11 12:40 UTC, pierrax commented on db/migrate/20230915094313_create_users_search_histories.rb
> +    create_table :users_search_histories do |t|
done

2023-10-12 09:07 UTC, fitchMitch approved these changes

2023-10-19 13:16 UTC, merged