813 Step 5 offer
betagouv/monstage pull request #1076
Opened 2023-10-10 09:16 UTC by pierrax

2023-10-12 06:55 UTC, fitchMitch requested changes

2023-10-12 06:55 UTC, fitchMitch commented on app/views/dashboard/internship_offers/_navigation.html.slim
> +      - if can?(:publish, @internship_offer) && !@internship_offer.drafted?
donc on ne peut pas supprimer une offre à l'état draft, c'est ça ?

2023-10-12 07:34 UTC, fitchMitch commented
C'est surtout une question plutôt qu'une demand de changement. Ca m'a paru bizarre.

2023-10-19 13:13 UTC, pierrax commented on app/views/dashboard/internship_offers/_navigation.html.slim
> +      - if can?(:publish, @internship_offer) && !@internship_offer.drafted?
yes la vue du brouillon de l'offre n'affiche pas ces boutons dans la maquette..

2023-11-07 15:09 UTC, merged