985 Add no application student reminder
betagouv/monstage pull request #1189
Opened 2024-01-24 09:59 UTC by pierrax

2024-01-24 10:54 UTC, fitchMitch requested changes

2024-01-24 10:54 UTC, fitchMitch commented on app/jobs/send_student_reminder_without_application_job.rb
> +class SendStudentReminderWithoutApplicationJob < ApplicationJob
SendReminderToStudentWithoutApplicdationJob est plus anglais

2024-01-24 10:54 UTC, fitchMitch commented on app/jobs/send_student_reminder_without_application_job.rb
> +    student = Users::Student.find(student_id)
il faudrait filtrer les kept pour la fin de l'année, histoire de ne pas envoyer de reminder à ceux qui ont quitté l'école

2024-01-24 10:54 UTC, fitchMitch commented on app/jobs/send_student_reminder_without_application_job.rb
> +        Services::SmsSender.new(phone_number: phone, content: content)
C'est mieux d'employer le job SendSms parce qu'on peut suivre les éventuelles erreurs et que ça décharge la prod

2024-01-25 14:02 UTC, pierrax commented on app/jobs/send_student_reminder_without_application_job.rb
> +    student = Users::Student.find(student_id)
Le reminder est envoyé 3 jours après la création du compte je ne pense qu'on puisse tomber dans ce cas

2024-01-25 14:07 UTC, pierrax commented on app/jobs/send_student_reminder_without_application_job.rb
> +        Services::SmsSender.new(phone_number: phone, content: content)
J'ai rajouté mais on est déjà dans un job asynchrone

2024-01-30 08:42 UTC, fitchMitch approved these changes

2024-02-13 08:44 UTC, merged