MS3-1027 : fix(parallel invitations) : when an invitation is already accepted or refused, it is not accepted or refused a second time anymore
betagouv/monstage pull request #1200
Opened 2024-02-05 10:21 UTC by fitchMitch

2024-02-07 15:48 UTC, pierrax requested changes

2024-02-07 15:48 UTC, pierrax commented on app/controllers/dashboard/team_member_invitations_controller.rb
> +      if @team_member_invitation.may_accept_invitation? ||
y a que 3 états, pourquoi pas if !pending ?

2024-02-08 09:53 UTC, fitchMitch commented on app/controllers/dashboard/team_member_invitations_controller.rb
> +      if @team_member_invitation.may_accept_invitation? ||
`if ! `==>` if `, et sinon ok !

2024-02-10 15:41 UTC, pierrax approved these changes

2024-02-15 13:28 UTC, merged