1045 Separate stats from internship_offer
betagouv/monstage pull request #1205
Opened 2024-02-09 17:16 UTC by pierrax

2024-02-12 12:35 UTC, fitchMitch requested changes

2024-02-12 12:35 UTC, fitchMitch commented on app/models/internship_offer_stats.rb
> +  def recalculate
recalculate ? ==> update tout simplement ?

2024-02-12 12:35 UTC, fitchMitch commented on app/models/internship_offer.rb
> +    need_update! if requires_updates?
peut-être que je me trompe, mais le update_columns supprimé n'est pas remplacé .... Si tu penses qu'il ne sert à rien, met un TODO, on verra après mais tout de suite, je ne prendrais pas de risque

2024-02-12 12:35 UTC, fitchMitch commented on test/controllers/dashboard/internship_offers/update_test.rb
> +        puts '***********'
nettoyage puts requis

2024-02-12 12:35 UTC, fitchMitch commented on app/models/internship_offer_stats.rb
> +      update_needed: update_needed?
avec update_needed,dans les stats, on ne mélangerait pas les torchons avec les serviettes ? Ce champ devrait être sur internship_offer au mieux, mais à l'heure actuelle, il est sur l'état aasm_state de l'offre (et ça me parait pas si mal). C'est son état . Pourquoi avoir changé ?

2024-02-12 12:35 UTC, fitchMitch commented on test/factories/internship_offers.rb
> +    #after(:create) do |internship_offer, params|
supprimer ces lignes de commentaire

2024-02-12 12:35 UTC, fitchMitch commented on test/models/reporting/internship_offer_aggregate_functions_test.rb
> +        #assert_equal 2, agri_stats.total_male_applications_count
pourquoi cette ligne ci est-elle en commentaire ?

2024-02-14 10:29 UTC, pierrax commented on app/models/reporting/internship_offer.rb
> +        .joins("INNER JOIN internship_offer_stats ON internship_offer_stats.internship_offer_id = internship_offers.id")
La relation est nommée :stats et ça met le bazar

2024-02-15 08:47 UTC, fitchMitch approved these changes

2024-02-15 10:59 UTC, merged