Us/operator search as visitors
betagouv/monstage pull request #190
Opened 2020-09-21 08:17 UTC by fitchMitch

2020-09-21 09:06 UTC, fitchMitch commented
Le résultat n'est pas atteint : attendre de nouveaux push !

2020-09-21 15:30 UTC, mfo commented
attention le chgmt de type de requete (operator_query -> visitor_query) ne permet plus de filtrer les offres des operateurs sur leurs tableau de bord. que penses-tu de creer un autre finder (genre reserver aux offreur/operateur a caller ds le controller dashboard::internship_offer#index)?

2020-09-21 15:32 UTC, mfo commented on app/libs/finders/user_typable_internship_offer.rb
> +      Users::Operator.name => :visitor_query,
cf mon commentaire sur la pr. on perd le fait de filtrer les offres des operateur sur leur vue d'admin. il est tmps de splitter ce comportement (p-e/certainement le finder listable aussi a adapter) ScboolUserOffer / OfferManagementInternshipOffer ?

2020-09-21 15:32 UTC, mfo requested changes
va falloire refactorer non (possible que je sois perdu)

2020-09-22 08:01 UTC, fitchMitch commented
@mfo , j'étais très surpris de la perte de fonctionnalité réclamée pour les opérateurs. C'est ce qui m'a amené à être bien lourd auprès de Brice afin de m'assurer que oui, on voulait perdre chez l'opérateur la possiblité de filtrer parmi ses propres offres.... dans son dashboard ! Peut-être fallait-il comprendre que la rechercher de l'acceuil une fois logué devait donner les résultats qu'un visiteur trouve lui aussi. J'aurais confondu... Je me refais préciser

2020-09-22 09:45 UTC, fitchMitch commented
Le mieux consiste encore à oublier cette branche . J'en refais une autre

2020-09-22 13:15 UTC, merged