Us/interfaces update for employers validation flow
betagouv/monstage pull request #195
Opened 2020-09-30 09:46 UTC by fitchMitch

2020-09-30 13:01 UTC, fitchMitch commented
C'est reviewable 
Voici un lien pour la review fonctionnelle : https://monstage-us-interfaces--qirlp1.herokuapp.com/dashboard/internship_offers/4/internship_applications?order=internshipDate#internship-application-2

2020-10-02 11:54 UTC, mfo commented on app/front_assets/controllers/applications_order_controller.js
> +import { Controller } from 'stimulus';
@fitchMitch pas certains qu'i faille du JS la dessus, se sont des liens non? prk impliquer du JS ?

2020-10-02 11:56 UTC, mfo commented on app/front_assets/controllers/internship_application_index_controller.js
> +    const $collapsibleTarget = $(this.collapsibleTarget);
@fitchMitch encore, prk faire ca en JS ? plutot coté back non ?

2020-10-02 11:57 UTC, mfo commented on app/front_assets/stylesheets/pages/internship_applications.scss
> +}
@fitchMitch pas certains. que se soit necssaire ici non ? jvois pas d'appel ds le code

2020-10-02 11:58 UTC, mfo commented on app/models/internship_offer.rb
> +  # end
deadcode, a virer

2020-10-02 12:01 UTC, mfo commented on db/structure.sql
> +    daily_hours text[] DEFAULT '{}'::text[]
oula pas necessaire ici

2020-10-02 12:02 UTC, mfo commented on infra/review/structure-review.sql
> +    daily_hours text[] DEFAULT '{}'::text[]
idem, si t'as pas de chgmt de bdd. jpense que les structure/structure-review ne devraient pas bouger

2020-10-02 12:02 UTC, mfo requested changes
eviter de faire du JS qd c'est pas necessaire.

2020-10-02 12:19 UTC, fitchMitch commented on app/front_assets/stylesheets/pages/internship_applications.scss
> +}
oups, c'est un héritage mal géré de la branche de maxime : je retire

2020-10-02 15:59 UTC, mfo approved these changes

2020-10-05 07:32 UTC, merged