Us/employer signs applications
betagouv/monstage pull request #217
Opened 2020-10-28 13:08 UTC by fitchMitch

2020-10-28 13:15 UTC, fitchMitch commented on app/views/dashboard/internship_agreements/index.html.slim
> +tr
Si l'index est partagé avec une autre vue qui l'incluerait, on oblige ici à utiliser un tableau... Je ne sais  pas si ce n'est pas un peu gênant

2020-10-28 13:15 UTC, fitchMitch commented on app/models/internship_agreement.rb
> +  scope :by_user_and_offers, lambda { |user:, offers: InternshipOffer.all|
Certainement sujet à discussion ...

2020-10-28 13:15 UTC, fitchMitch commented on app/libs/finders/internship_offer_publisher.rb
> +        active: proposed_offers,
je n'utilise que approved, le reste, c'est un peu du code éventuellement pour le futur. C'est le nom all_states_counter qui m'a forcé la main. Je voulais signaler que les calculs étaient fait à l'avance , i.e. avant de cliquer sur la tabulation

2020-10-28 16:09 UTC, mfo commented on app/libs/finders/internship_offer_publisher.rb
> +        active: proposed_offers,
tu peux virer le reste si c'est pas utilisé

2020-10-28 16:13 UTC, mfo commented on app/libs/finders/internship_offer_publisher.rb
> +                     .where(applications_at[:aasm_state].eq('approved'))
je regarde si il y a pas une option genre user.internship_applications.approved

2020-10-28 16:16 UTC, mfo commented on app/views/dashboard/internship_offers/_tabs.html.slim
> +  - if ENV.fetch('CONVENTION_ENABLED', false)
```suggestion
  - if ENV['CONVENTION_ENABLED']
```

2020-10-28 16:17 UTC, mfo commented on app/views/dashboard/internship_offers/_tabs.html.slim
> +  - if ENV.fetch('CONVENTION_ENABLED', false)
l'idée est de resté raccord ac le reste de l'app

2020-10-28 16:37 UTC, mfo requested changes
l'implementation graphique du design de la modal est approximatif.

ex: 
* taille du titre plus petite par rapport a la maquette
* couleur de la croix pr fermer la modal
et d'autres j'imagine

2020-10-29 06:20 UTC, mfo commented on app/libs/finders/internship_offer_publisher.rb
> +                     .where(applications_at[:aasm_state].eq('approved'))
@fitchMitch sembe fonctionner Users::Employer.first.internship_applications.approved

2020-10-29 06:21 UTC, mfo commented on app/controllers/dashboard/internship_offers_controller.rb
> +      @all_states_counter = @finder.all_states_counter
idee a explorer, p-e extraire ces requetes ds un TabCounterFinder ou qqch comme ca

2020-10-29 06:22 UTC, mfo commented on app/controllers/dashboard/internship_offers_controller.rb
> +      )
ca m'etonne que pour ttes les "pages" (offre+filtre) on requete les agreements. a voir si il faudrait pas extraire cette logique ailleurs... mais ou

2020-10-29 06:23 UTC, mfo commented on app/views/dashboard/internship_agreements/index.html.slim
> +tr
pas grave, pr les tableau non necessaire, ajouter role="presentation"

2020-10-29 06:24 UTC, mfo commented on app/views/dashboard/internship_offers/_table.html.slim
> +    tbody= render template: "dashboard/internship_agreements/index"
pas certains que se soit au bon endroit. je pense il faudrait extraire ca dans un app/views/internship_agreement/index.html

2020-10-29 09:06 UTC, fitchMitch commented on app/libs/finders/internship_offer_publisher.rb
> +                     .where(applications_at[:aasm_state].eq('approved'))
Oui, c'est vrai, mais après c'est le InternshipOffer.kept qu'il faut intégrer ...

2020-10-29 09:23 UTC, fitchMitch commented on app/views/dashboard/internship_offers/_table.html.slim
> +    tbody= render template: "dashboard/internship_agreements/index"
Je déplace

2020-10-29 12:44 UTC, mfo requested changes
@pierrax @fitchMitch je pense que l'implemn actuelle tend a se questionner autour de "l'archi" ; en gros echanger autour de ça (j'ai l'impression qu'on traite des intership_application en fct de l'utilisateurs. un peu comme les intership_offers ; p-e que le moment de propsoer de creer un namespace dedié a ca  (au meme titre qu'on gere des offres de stages par status (dashboard/internship_offers?filter), p-e que la gestion des agreements est associé aux internship applications (dashboard/internship_applications). genre creer un namespace qui permet de filtrer par status (candidature : en attente de réponse, historisée (refusé ou passé), accepté/convention a etablir) / bref j'ai l'impression qu'il est tmps d'isoler ca proprement)

2020-10-30 14:10 UTC, mfo commented on app/views/dashboard/internship_offers/_table.html.slim
> +  - else
pas a sa place pr le moment

2020-10-30 14:11 UTC, mfo commented on app/views/dashboard/internship_offers/_tabs.html.slim
>                         class: "d-flex h-100 px-2 px-sm-3 nav-link #{is_active ? 'active' : ''}" do
a remonter ds views/dashboard (partagé entre les deux controller

2020-11-02 10:44 UTC, fitchMitch commented on app/controllers/dashboard/internship_offers_controller.rb
> +      @all_states_counter = @finder.all_states_counter
Je ne sais pas trop quoi faire : écarter le tab counter des méthodes/requêtes auxquelles il fait reféférence va rendre les appels spécifiques aux méthodes internes de InternshipOfferPublisher assez verbeuse et je pense qu'on va perdre en lisibilité, mais je veux bien en discuter, naturellement

2020-11-02 16:48 UTC, merged