Us/a11y tests extend to latest pages
betagouv/monstage pull request #234
Opened 2020-12-07 10:07 UTC by fitchMitch

2020-12-14 12:41 UTC, mfo requested changes

2020-12-14 12:41 UTC, mfo commented on test/system/w3c/dashboard_test.rb
> +    if ENV['CONVENTION_ENABLED']
```suggestion
    if ENV['CONVENTION_ENABLED']
```

2020-12-14 12:41 UTC, mfo commented on test/system/w3c/dashboard_test.rb
> +    end
```suggestion
```

2020-12-14 16:33 UTC, mfo commented
@fitchMitch ; je me suis permis de virer le if ENV['CONVENTION_ENABLED']. tu as bien trouvé des bugs w3c/accessibilité ;-)

2020-12-17 17:54 UTC, fitchMitch commented
Bonne grosse erreur avec un énorme git rebase origin/master : NE PAS MERGER ! (je refais le travail en cherry picking)

2020-12-17 20:47 UTC, closed without merging