Fix/no internship school weeks messages
betagouv/monstage pull request #264
Opened 2021-01-21 17:00 UTC by fitchMitch

2021-01-27 08:19 UTC, mfo commented on app/models/user.rb
> +    school.try(:weeks).none? { |week| week.in?(Week.selectable_from_now_until_end_of_school_year) }
un join plutot qu'iterer sur une liste ac des requetes a chaque iteration.
aussi, ca sent le bug... Week.selectable_from_now_until_end_of_school_year ; mais plutot qqch comme Week.for_current_school_year

2021-01-27 08:20 UTC, mfo commented on app/views/internship_offers/index.html.slim
> +- if @internship_offers.blank?
en gros en l'absence d'offre on considere qu'il y a pas de semaine? louche. possible qu'il n'y aie juste pas d'offre

2021-01-27 08:39 UTC, mfo commented on app/views/internship_applications/forms/_student_missing_school_weeks.html.slim
> +- if current_user && current_user.missing_school_weeks? && current_user.missing_weeks_school_id.nil?
:/comprends pas l'intention  :/ possible de mettre ca ds un helper qui explicite le propos?

2021-01-27 08:44 UTC, mfo requested changes
- app/models/user.rb: possiblement l'introduction d'un bug, a fixer
- app/views/internship_offers/index.html.slim  ; possiblement l'introduction d'un bug, a fixer

deja fixer ces probs + apres on en discute, jvois pas rien coté cron et personnel pedago

2021-01-27 09:30 UTC, fitchMitch commented on app/models/user.rb
> +    school.try(:weeks).none? { |week| week.in?(Week.selectable_from_now_until_end_of_school_year) }
Effectivement, je voulais créer un message pour le cas où un étudiant voudrait un stage sans pouvoir l'avoir car les semaines restantes de l'année n'aurait pas été éligible (non déclarée comme telle par le chef d'établissement). A la réflexion c'est une erreur. Un chef d'établissement remplit les semaines une fois pour toute, mais pas à la demande. Je fais la partie requête réclamée.

2021-01-27 09:35 UTC, fitchMitch commented on app/views/internship_offers/index.html.slim
> +- if @internship_offers.blank?
Acutellement , quand l'élève ne voit pas d'offre, aucun message n'en explique la raison. Il voit juste 0 offres sachant qu'il vient peut etre d'une page "vissteur"qui en propose plein dans sa région. J'ai supposé trop rapidement que si ça se produisait, c'était que le chef d'établissement n'avait pas saisi de semaine de stage. Il faut pourtant expliquer ce 0 sinon, nous aurons des remontées de bugs.

2021-01-27 12:35 UTC, mfo commented on app/views/internship_offers/index.html.slim
> +- if @internship_offers.blank?
ligne 22, `p.col-12[style='color: gray'] Aucune offre disponible` ?

2021-01-27 12:36 UTC, mfo commented on app/models/user.rb
> +                                  .zero?
je ne vois pas de notion utilisateur, la query est globale, bug?
en pseudo code `school.weeks.selectable_on_school_year?`

2021-01-27 12:39 UTC, mfo commented on app/views/internship_offers/index.html.slim
> +  = render partial: "internship_applications/forms/student_missing_school_weeks"
```suggestion
```

2021-01-27 12:41 UTC, mfo commented on app/views/internship_applications/forms/_student_missing_school_weeks.html.slim
> +- if current_user && current_user.missing_school_weeks? && current_user.missing_weeks_school_id.nil?
jviens de relire ; 
1. current_user_present?
2. no_school_weeks_for_current_user?
3. user_never_notified_school_manager_for_missing_school_weeks?

?

2021-01-29 08:43 UTC, mfo commented on app/libs/triggers/school_missing_weeks_reminder.rb
> -      School.without_weeks
@fitchMitch la methode n'est plus utilisée, tu peux la virer

2021-02-01 14:10 UTC, merged