Us/school track filters on mobile
betagouv/monstage pull request #288
Opened 2021-02-21 11:03 UTC by fitchMitch

A discuter, mais je ne suis pas content de la partie React qui n'est pas générique, alors que je ne suis pas loin

2021-02-22 12:19 UTC, mfo requested changes
RAS sur l'implem
en revanche deux couac graphiques : 
1. l'affichage du filtre via select devrait etre present sur mobile uniquement (la on l'a des que screem sm)
2. dmg de pas mettre le floating label

2021-02-22 17:00 UTC, fitchMitch commented
C'est fait !

2021-03-08 15:11 UTC, mfo commented on app/views/common/_filter_with_mobile_alternative.html.slim
> +  .col-8.offset-2.form-group.text-center.center-text.custom-label-container
```suggestion
  .col-12.col-sm-8.offset-sm-2.form-group.text-center.center-text.custom-label-container
```

2021-03-08 15:14 UTC, mfo commented on app/views/common/_filter_with_mobile_alternative.html.slim
> +  .col-12.col-sm-8.offset-sm-2.form-group.text-center.center-text.custom-label-container
```suggestion
  .col-12.m-0.col-sm-8.offset-sm-2.form-group.text-center.center-text.custom-label-container
```

2021-03-08 15:14 UTC, mfo commented on app/views/common/_filter_with_mobile_alternative.html.slim
> +  .col-12.m-0.col-sm-8.offset-sm-2.form-group.text-center.center-text.custom-label-container
```suggestion
  .col-12.m-0.form-group.text-center.center-text.custom-label-container
```

2021-03-08 15:15 UTC, merged