Us/anonymize fixed and extended to class rooms
betagouv/monstage pull request #302
Opened 2021-03-11 13:31 UTC by fitchMitch

2021-03-11 16:09 UTC, mfo requested changes
sur le naming c'est domage : 

- student.anonymize / class_room.anonymize! (ac un bang)
- student.anonymisze (set un flag anonymized a true) ; class_room.anonymize (set un champs de type date, qui plus est le discarded_at est utilisé par la gem discard pr faire du soft delete, c'est confusant). 

faudrait se calquer sur le mechanisme de student

2021-03-12 11:00 UTC, fitchMitch commented
Si le signalement de la date n'est pas associé à l'archivage/anonymisation, comment va-t-on entretenir les stats sur le nombre de classes année par années ?

2021-03-17 07:07 UTC, mfo commented on app/libs/school_year/archiver.rb
> +      archive_class_rooms
trouvé ca bizarre le &&
```suggestion
      ActiveRecord::Base.transaction do
        archive_students
        archive_class_rooms
      end
```

2021-03-17 07:08 UTC, mfo approved these changes
@fitchMitch top! idéalement merge mon commentaire (en gros, on veut que le archive se passe en entier ou pas dutout. mais pas d'erreur intermediaire persisté en bdd)

2021-03-17 16:57 UTC, merged