Fix/mailers previews
betagouv/monstage pull request #356
Opened 2021-05-31 10:00 UTC by fitchMitch

2021-05-31 10:02 UTC, fitchMitch commented
Inconvénient non négligeable : la feature est réservée au développeur sous cette forme

2021-06-08 10:57 UTC, mfo requested changes
prk pas ds les seeds pr partager les data?

2021-06-08 14:20 UTC, fitchMitch commented
Oui, on peut, mais il faut surtout créer une route pour accéder aux pages web de démo , maintenant que j'y pense

2021-06-08 15:04 UTC, mfo commented
on reste en attente la dessus non ?

2021-06-15 04:57 UTC, mfo commented on test/mailers/previews/employer_mailer_preview.rb
> +    FactoryBot.create(:weekly_internship_application, aasm_state, student: student, internship_offer: internship_offer )
evitons les factories. risque de devenir compliqué ac le staging au bout d'un moment

2021-06-15 04:57 UTC, mfo commented on test/mailers/previews/main_teacher_mailer_preview.rb
> +    )
same, a deplacer ds les seeds

2021-06-15 04:57 UTC, mfo commented on test/mailers/previews/main_teacher_mailer_preview.rb
> +    FactoryBot.create(:weekly_internship_application, aasm_state, student: student, internship_offer: internship_offer )
same same

2021-06-15 04:57 UTC, mfo commented on test/mailers/previews/school_manager_mailer_preview.rb
> +    )
same

2021-06-15 04:57 UTC, mfo commented on test/mailers/previews/student_mailer_preview.rb
> +    FactoryBot.create(:weekly_internship_application, aasm_state, student: student, internship_offer: internship_offer )
same

2021-06-15 04:58 UTC, mfo requested changes
virer les factory bot .create (deplacer ds les seeds)

2021-06-25 07:08 UTC, mfo approved these changes
ok pr moi

2021-06-28 07:10 UTC, merged