Us/central administrator statistics
betagouv/monstage pull request #375
Opened 2021-06-15 07:53 UTC by fitchMitch

2021-06-15 11:06 UTC, mfo requested changes
0 change?

2021-06-16 17:37 UTC, fitchMitch commented
some actually

2021-06-17 12:42 UTC, mfo commented on app/models/ability.rb
> +    can %i[index], Acl::Reporting
a la limite appliquer en plus le &:allowed? (en préalable, renommer en &:allowed_statistician? + ajouter le &:allowed_ministry_statistician)

2021-06-17 12:44 UTC, mfo commented on app/models/internship_offer.rb
> +    where(group_id: user.ministry.id)
```suggestion
    where(group_id: user.ministry_id)
```

2021-06-17 12:44 UTC, mfo commented on app/controllers/reporting/internship_offers_controller.rb
> +      params.merge!(group: current_user.ministry.id) if current_user.ministry_statistician?
```suggestion
      params.merge!(group: current_user.ministry_id) if current_user.ministry_statistician?
```

2021-06-17 12:45 UTC, mfo commented on app/controllers/reporting/internship_offers_controller.rb
> +      params.merge!(group: current_user.ministry.id) if current_user.ministry_statistician?
```suggestion
      params.merge!(group: current_user.ministry_id) if current_user.ministry_statistician?
```

2021-06-17 12:45 UTC, mfo commented on app/models/reporting/internship_offer.rb
> +      where(group_id: user.ministry.id)
```suggestion
      where(group_id: user.ministry_id)
```

2021-06-17 12:45 UTC, mfo commented on app/models/reporting/internship_offer.rb
> +      where(group_id: user.ministry.id)
```suggestion
      where(group_id: user.ministry_id)
```

2021-06-17 13:07 UTC, mfo approved these changes

2021-06-22 08:13 UTC, merged