Us/visitor gets back to offer
betagouv/monstage pull request #391
Opened 2021-06-29 09:14 UTC by fitchMitch

2021-07-02 13:35 UTC, pierrax commented on app/models/user.rb
> +  def reset_targeted_offer_id!
avec le ! je m'attends à recevoir l'objet modifié

2021-07-02 16:17 UTC, fitchMitch commented on app/models/user.rb
> +  def reset_targeted_offer_id!
yes ! Merci pour la revue ! Je fais le changement

2021-07-05 11:38 UTC, mfo commented on app/controllers/users/registrations_controller.rb
> +      @targeted_offer_id = params.dig(:user, :targeted_offer_id)
```suggestion
      targeted_offer_id = params.dig(:user, :targeted_offer_id)
```

2021-07-05 11:39 UTC, mfo commented on app/controllers/users/registrations_controller.rb
> +      options = options.merge(targeted_offer_id: @targeted_offer_id) if @targeted_offer_id
```suggestion
      options = options.merge(targeted_offer_id: targeted_offer_id) if targeted_offer_id
```

2021-07-07 17:36 UTC, fitchMitch commented on app/controllers/users/registrations_controller.rb
> +      @targeted_offer_id = params.dig(:user, :targeted_offer_id)
non, non, j'en ai besoin dans la vue...

2021-07-15 11:31 UTC, mfo requested changes
sry j'ai mis de tmps a comprendre mais il manque un edge case : l'utilisateur foire son inscription (ex: mauvaise date: 00/00/0000). on rerend le partial new, le @targeted_offer_id n'existe pas. p-e utiliser le params.dig(:user, :targeted_offer_id) partout ?

2021-08-09 13:59 UTC, fitchMitch commented
Hello ! Je ne retrouve pas un commentaire que je pensais avoir laissé : je n'arrive pas à concilier toutes les contraintes pour le edge case que tu signales : pas de stockage dans la session (:store_user_location!, store_location_for) + une seule solution. Si une erreur se produit dans create, l'erreur est traitée dans la gem devise et la possibilité de manipuler des options supplémentaires dans le render :new n'est pas accessible, sauf monkey patch...
```
def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end
```

2021-08-10 12:23 UTC, mfo commented
pairing. todo

2021-08-11 07:16 UTC, merged