190 évolution du parcours lors d'une candidature annulée par un élève
betagouv/monstage pull request #649
Opened 2022-04-13 09:52 UTC by bricedurand

2022-04-14 08:17 UTC, fitchMitch requested changes

2022-04-14 08:17 UTC, fitchMitch commented on app/mailers/employer_mailer.rb
> +         subject: 'Une candidature a été annulée')
En fait et bizarrementf, cette modif n'est pas idéale : pour améliorer notre score chez notre pretataire de mail, nous observons la règle de n'envoyer de mails que lorsque le sujet du mail compte entre 35 et 50 caractères

2022-04-14 09:33 UTC, bricedurand commented on app/mailers/employer_mailer.rb
> +         subject: 'Une candidature a été annulée')
Ok je remets le "Information" qui était déjà là, et préviens la comm qui décide des titres des emails

2022-04-15 09:25 UTC, fitchMitch approved these changes

2022-04-19 08:27 UTC, merged