411 suppression de la voie pro phase 3
betagouv/monstage pull request #881
Opened 2022-12-14 12:41 UTC by bricedurand

Reste encore la partie refactoring des classes InternshipOffer, InternshipOfferInfos et InternshipApplication :
- Supprimer ou renommer les occurrences de WeeklyFramed
- Supprimer les types pour les classes InternshipOfferInfos et InternshipApplication
- Renommer tous les weekly dans les noms de variables et factories

2022-12-14 17:57 UTC, fitchMitch requested changes
C'est surtout le filtrage de la recherche qui m'inquiète, mais sinon très peu de choses à redire. Des questions. 
Nice job

2022-12-14 17:57 UTC, fitchMitch commented on app/front_assets/controllers/internship_offer_infos_controller.js
> +    const inducedType = `${this.baseTypeValue}s::WeeklyFramed`;
mais ça peut être autre chose qu' 
IntershipOffers::WeeklyFramed ?

2022-12-14 17:57 UTC, fitchMitch commented on app/libs/finders/context_typable_internship_offer.rb
ici la suppression m'inquiète car la méthode était mal nommée , plus exactement elle couple plusieurs choses autour de la filère. Il me semble que l'on ne filtre plus sur ignore_already_applied et uncompleted_with_max_candidates, mais tu me diras

2022-12-14 17:57 UTC, fitchMitch commented on app/libs/presenters/class_room.rb
>              .order(:name)
sans group_by, la forme du résultat change, non? Ca marche dans l'interface ?

2022-12-14 17:57 UTC, fitchMitch commented on app/models/ability.rb
>    def student_can_apply?(internship_offer:, student:)
C'est un petit peu  plus difficile à lire mais surtout, je vois des tests qui disparaissent ici. Pourquoi ?

2022-12-14 17:57 UTC, fitchMitch commented on db/migrate/20221104091520_offres_voie_pro.rb
> +  def up
Aujourd'hui on passe toutes les migrations de data hors db/migrate dans des tâches.... on peut utiliser TaskManager qui permet de ne jouer une tâche qu'une seule fois et dans un job de surcroît

2022-12-14 17:57 UTC, fitchMitch commented on test/factories/air_table_records.rb
> -    school_track { "MyText" }
je n'ai pas beaucoup trempé dans les histoires de AirTable, donc je m'en remets à toi : est-ce que school_track n'aurait pas de sens dans le contexte des stages de nos partenaires ?

2022-12-14 17:57 UTC, fitchMitch commented on test/factories/internship_offers.rb
> +    description { 'Lorem ipsum dolor' }
c'est pourtant vrai : ça manquait !

2022-12-14 17:57 UTC, fitchMitch commented on db/seeds.rb
> +  class_room_1 = ClassRoom.first
nice job

2022-12-14 17:58 UTC, fitchMitch commented
C'est bien d'avoir loti le travail. Le plan est clair

2022-12-15 14:58 UTC, bricedurand commented on app/front_assets/controllers/internship_offer_infos_controller.js
> +    const inducedType = `${this.baseTypeValue}s::WeeklyFramed`;
Non en effet, c'était pour éviter tout bug. Je fais la suppression ce n'est pas bien compliqué

2022-12-15 14:59 UTC, bricedurand commented on app/libs/presenters/class_room.rb
>              .order(:name)
Effectivement, j'ai changé l'interface pour que ça soit cohérent

2022-12-15 15:00 UTC, bricedurand commented on app/models/ability.rb
>    def student_can_apply?(internship_offer:, student:)
Comme free_date n'existe plus, les conditions sautent également, sauf celle pour les offres "weekly"

2022-12-15 15:01 UTC, bricedurand commented on test/factories/air_table_records.rb
> -    school_track { "MyText" }
À vérifier oui, je le remets en attendant

2022-12-15 15:06 UTC, bricedurand commented on db/migrate/20221104091520_offres_voie_pro.rb
> +  def up
La migration n'est jouée qu'une fois également, et a le mérite d'être tracée dans le temps avec le timestamp, et se retrouve facilement. Quant au job ça ne me paraît pas gênant dans ce cas, étant donné le faible volume.

Si tu y tiens va pour la tâche..

2022-12-20 11:20 UTC, bricedurand commented on app/front_assets/controllers/internship_offer_infos_controller.js
> +    const inducedType = `${this.baseTypeValue}s::WeeklyFramed`;
Bon finalement autant supprimer le champ type de InternshipOfferInfos, qui nécessite un refactoring un peu plus conséquent. Donc je vous propose de faire ça dans un deuxième temps

2022-12-21 08:26 UTC, bricedurand commented on app/libs/finders/context_typable_internship_offer.rb
Effectivement je suis allé un peu vite sur cette méthode, je revois ça

2022-12-21 08:33 UTC, bricedurand commented on app/models/ability.rb
>    def student_can_apply?(internship_offer:, student:)
Les deux conditions suivantes sautent car la méthode "applicable?" renvoie toujours vrai lorsqu'il n'y a plus d'offres FreeDate.

`return true if student.try(:class_room).nil?
return true if student.try(:class_room).try(:applicable?, internship_offer)`

2022-12-21 10:46 UTC, bricedurand commented on app/libs/finders/context_typable_internship_offer.rb
À mon avis ce n'est pas un problème car le filtre par filière n'existe déjà plus sur la recherche ni le tableau de bord employeur. Donc le paramètre school_track n'est pas envoyé, et cette méthode n'est pas appelée.

Ca peut cacher une régression existante, mais ça sort du cadre de ce ticket

2022-12-26 22:58 UTC, merged