561 Import students by teacher
betagouv/monstage pull request #890
Opened 2023-01-03 09:23 UTC by pierrax

2023-01-03 14:27 UTC, fitchMitch requested changes
il  y a un fichier dump.rdb au fond de la PR.... C'est utile ?

2023-01-03 14:27 UTC, fitchMitch commented on app/controllers/dashboard/schools/class_rooms/students_controller.rb
> +          puts student.errors.full_messages
une ligne oubliée

2023-01-03 14:27 UTC, fitchMitch commented on app/controllers/dashboard/schools/class_rooms/students_controller.rb
> +          password: Devise.friendly_token.first(8),
commentaire personnel sans contenu : bon courage pour le prof avec ce password

2023-01-03 14:27 UTC, fitchMitch commented on app/mailers/student_mailer.rb
> +    mail(to: @student.email,
juste pour confirmation:  l'élève a toujours un email dans ce cas de figure, n'est-ce pas ?

2023-01-03 14:27 UTC, fitchMitch commented on app/models/user.rb
> +    return if created_by_teacher
c'est pas `skip_confifmation!` ?

https://stackoverflow.com/questions/30475785/devise-skip-confirmation-notification-before-save

2023-01-03 14:27 UTC, fitchMitch commented on app/models/user.rb
>        self.confirm
voir plus haut, toujours dans la meme intenttion. Tmtc

2023-01-03 14:27 UTC, fitchMitch commented on app/views/devise/passwords/edit.html.slim
> +                    html: { method: :put}) do |f|
:patch ?

2023-01-06 10:12 UTC, pierrax commented on app/controllers/dashboard/schools/class_rooms/students_controller.rb
> +          password: Devise.friendly_token.first(8),
C'est temporaire et invisible, on leur demande de modifier direct.

2023-01-06 10:12 UTC, pierrax commented on app/mailers/student_mailer.rb
> +    mail(to: @student.email,
yes

2023-01-06 10:13 UTC, pierrax commented on app/models/user.rb
> +    return if created_by_teacher
On peut faire ça mais il faut rajouter un callback before save ce qui parait encore plus lourd

2023-01-06 10:14 UTC, merged