631 Revamp page show offer
betagouv/monstage pull request #918
Opened 2023-02-09 15:17 UTC by pierrax

2023-02-09 16:59 UTC, fitchMitch requested changes

2023-02-09 16:59 UTC, fitchMitch commented on app/front_assets/components/InternshipOfferFavoriteButton.jsx
> +      { isDisabled ? (
ou bien
` isDisabled && (composant jsx) `

2023-02-09 16:59 UTC, fitchMitch commented on app/views/dashboard/internship_offers/_unpublish_form.html.slim
>  div id="pub_frag_#{dom_id(@internship_offer)}"
dom_id : super !

2023-02-09 16:59 UTC, fitchMitch commented on app/views/internship_offers/_show_details.html.slim
> +  .col-12.py-2
un petit presenter, ce serait pas du luxe, non ?

2023-02-10 10:40 UTC, fitchMitch approved these changes

2023-02-14 10:19 UTC, pierrax commented on app/front_assets/components/InternshipOfferFavoriteButton.jsx
> +      { isDisabled ? (
y a une condition ternaire ici

2023-02-14 10:20 UTC, merged