Ms3 688 offreur parcours de candidature acceptee
betagouv/monstage pull request #974
Opened 2023-04-24 15:39 UTC by fitchMitch

2023-04-26 14:40 UTC, pierrax commented on app/controllers/dashboard/internship_offers/internship_applications_controller.rb
> +        @received_internship_applications = @internship_applications.where(aasm_state: received_states)
y a pas moyen de faire @internship_application.received ?

2023-04-26 15:48 UTC, pierrax requested changes

2023-04-26 15:48 UTC, pierrax commented on app/libs/presenters/internship_offer.rb
> +    def entreprise
doublon avec le ligne 15

2023-04-26 15:48 UTC, pierrax commented on app/libs/school_year/base.rb
> +      when september_to_december, june_to_august
il ne faudrait pas dans ce faire june_to_december ?

2023-04-26 15:48 UTC, pierrax commented on app/mailers/concerns/layoutable.rb
> +    helper_method :p_styles, :head_styles, :span_bold, :p_cyclop_styles, :head_cyclop_styles,:hint_styles
😭

2023-04-26 15:48 UTC, pierrax commented on app/models/internship_application.rb
>      event :approve do
on s'attend à ce que ça soit l'employer qui 'approuve' la candidature

2023-04-26 15:48 UTC, pierrax commented on app/views/dashboard/internship_offers/internship_applications/user_internship_applications.html.slim
pourquoi pas dashboard/internship_applications/index ?

2023-04-26 15:48 UTC, pierrax commented on config/routes.rb
> +      get 'candidatures', to: 'internship_offers/internship_applications#user_internship_applications'
👍

2023-04-26 15:48 UTC, pierrax commented on public/assets/insta.png
on pourrait stripe les 3 logos

2023-04-26 15:51 UTC, fitchMitch commented on app/libs/finders/context_typable_internship_offer.rb
> +      query.merge(query.where(employer_hidden: false))
j'achète

2023-04-26 15:53 UTC, fitchMitch commented on app/models/internship_application.rb
> +  scope :expiration_extended, lambda {
j'achète

2023-04-26 15:53 UTC, fitchMitch commented on app/models/internship_application.rb
>      event :approve do
after_employer_validation_notifications ?

2023-04-26 15:55 UTC, fitchMitch commented on public/assets/insta.png
pô faux

2023-04-26 15:59 UTC, fitchMitch commented on app/libs/finders/context_typable_internship_offer.rb
> +      query.merge(query.where(employer_hidden: false))
ok

2023-04-26 16:15 UTC, fitchMitch commented on app/libs/finders/tab_employer.rb
> +      return 0 if user.operator?
je crois que les opérateurs ont accès à des vues où on va afficher des macarons jaune notifiant le travail à faire. En matière de conventions, les opérateurs d'assocation ne peuvent pas avoir d'alertes de ce type

2023-04-26 16:18 UTC, fitchMitch commented on app/libs/presenters/week_list.rb
> +    def short_render_period(week_trunk)
à retirer parce que les specs ont changé en plus : c'est le lieu et plus les dates qui sont affichées

2023-04-27 08:44 UTC, fitchMitch commented on app/views/dashboard/internship_offers/internship_applications/user_internship_applications.html.slim
C'est une modification assez lourde je crois , mais qui fait véritablement sens

2023-04-27 09:16 UTC, fitchMitch commented on app/libs/school_year/base.rb
> +      when september_to_december, june_to_august
Done

2023-06-13 08:10 UTC, merged